<div class="container">
    <!--API_TRIM_START-->
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="bar">
                <div class="btn-group btn-breadcrumb">
                    <a href="<?php echo base_url(); ?>" class="btn" title="Blendedd"><i class="glyphicon glyphicon-home"></i></a>
                    <a href="javascript:;" class="btn">Privacy Policy</a>
                </div>
            </div>
        </div>
    </div>
    <!--API_TRIM_END-->
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="well background_white">
				<h4>Privacy Policy</h4>
				<p>This privacy policy is designed to inform users of the Blendded, Inc. website (the "Website") about how Blendedd, Inc. ("Blendedd" or "we") gathers and uses personal information submitted to and through the Website. Blendedd will take steps to protect user privacy consistent with this policy ("Privacy Policy") and applicable U.S. laws. </p>
				<p>In this Privacy Policy, "User" refers to any person viewing and/or using the Website or submitting any personal information to Blendedd through the Website or other means requested by Blendedd. By using the Website, you acknowledge that this Privacy Policy is part of our Website Terms of Use, and by accessing or using our Website, you agree to be bound by all of its terms and conditions, including this Privacy Policy.</p>
				<br />
				<h3>IF YOU DO NOT AGREE WITH THIS PRIVACY POLICY, PLEASE EXIT THE WEBSITE IMMEDIATELY.</h3>
				<br />
				<h3>What Data is Collected From Users ?</h3>
				<br />
				<p><b>Personal Information.</b> In order to access most of the Website's features, Users will be prompted to register an account by entering personal information into the Website, including the User's name and email address. If a User decides to use the Website to buy, rent, or otherwise conduct a financial transaction with another User through the Website, Blendedd will collect the User's credit card and bank account information, mailing address, and phone number to facilitate this transaction. Users may elect to store their credit card information in Blendedd's secure database. Blendedd may ask for additional identifying information from Users to help personalize each User's experience on the Website, but this information will not be required to use the Website. </p>
                <p>Blendedd will use the personal information collected from Users to provide our services to Users and enhance the Users' experience, including, but not limited to, administering contests, promotions, and other site features, processing Users' transactions, analyzing Website use, contacting Users about their orders and other products and services, resolving disputes, troubleshooting technical and other problems, enforcing Blendedd's agreements with Users, and customizing the Website's content, layout, and services. </p>
				<p>Users may visit the Website anonymously, but the services offered by Blendedd will be limited because identifying information is needed to facilitate most of the services of the Website.</p>
				<p><b>Web Tracking Information.</b> Blendedd and any contracted third-party service providers may use web tracking technologies in order to operate the Website efficiently and to collect data related to usage of the Website. Collected data may include browser history before and after using the Website, web browser preferences used to access the Website, IP addresses, pages visited, links clicked, and whether an email we've sent was opened. We may also collect information about actions that Users take interacting with the Website. Although we do not correlate tracking information to individuals, some information collected, such as IP addresses, will be unique.</p>
				<p>In order to collect this information and make the Website more efficient, we may store cookies on Users' computers. Cookies help us remember and process the items in your shopping cart. They are also used to help Blendedd understand Users' preferences based on previous or current site activity, which enables us to provide improved services. We also use cookies to help us compile aggregate data about Website traffic and interaction so that we can offer better site experiences and tools in the future. Cookies may be disabled in each User's web browser and, although some Website services will not function properly if cookies are disabled, orders may still be placed on the Website. </p>
				<p>We do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.</p>
				<br />
				<h3>Is Users' Data Shared With Others ?</h3>
				<br />
				<p><b>Why We Share and Use Data.</b> We store and use information in order to deliver the best website experience and service to the User. Other uses may include internal operational and administrative purposes and storing so that we may analyze and cater appropriate services or products for Users.</p>
				<p>We may share aggregated, non-personally identifiable information publicly and with our partners. This information will be consolidated from all Users and thus neither relates to nor identifies any individual.</p>
				<p>If Blendedd is involved in a merger, acquisition, or asset sale, we will continue to ensure the confidentiality of any personal information and give affected Users notice before personal information is transferred or becomes subject to a different privacy policy.</p>
				<p><b>For Legal Reasons.</b> We will share personal information with companies, organizations, or individuals outside of Blendedd if we believe that access, use, preservation, or disclosure of the information is necessary to: meet any applicable law, regulation, legal process, or enforceable governmental request; enforce applicable Terms of Use, including investigating potential violations; detect, prevent, or address fraud, security, or technical issues; or protect against harm to the rights, property, or safety of Blendedd, our Users, or the public, as required or permitted by law.</p>
				<p><b>With Other Users and Third Parties.</b> Other Users can only see the personal information that a User enters into his or her Website profile, which generally will include the User's name, email address, and city and state of residence, plus any additional information that a User voluntarily decides to include in the profile. Blendedd will not share a User's mailing address, phone number, or credit card information with other Users without the express consent of the User. Except as set forth above or as otherwise authorized by you, Blendedd will not disclose, sell, trade, or otherwise transfer personal information to any third party. Blendedd shall in no event be liable to you for any use or misuse of personal information by any third party with whom your personal information has been shared in accordance with the terms of this Privacy Policy.</p>
				<p>Web Tracking Information may be disclosed to third party contractors in order to analyze Website performance and User behavior and/or improve the Website. Some web tracking information, such as "Most Popular Listings," may be public and thus disclosed to all Users.</p>
				<p>Aggregate Information that does not contain personal information may be disclosed to any third parties, such as potential customers, business partners, advertisers, and funding sources, in order to describe our business and operations.</p>
				<br />
				<h3>Can Personal Information Be Changed and Removed from the Website ?</h3>
				<br />
				<p><b>Accessing, Modifying and/or Deleting Personal Information.</b> Users may review, update, correct, and/or delete personal information through the account management features available on the Website after they log into their Blendedd account. Users may also contact <b><a href="mailto:support@blendedd.com">support@blendedd.com</a></b> to request that their user profile or other personal information be deleted from the Website and/or removed from Blendedd mailing lists. Each email sent to Users also includes instructions for unsubscribing to Blendedd emails at the bottom of the email, and these requests will be processed as quickly as practicable. Blendedd reserves the right to verify User identity in such cases.</p>
				<p>Even after account modification or removal, copies of previous information may remain on the Website to the extent that it had been previously shared with other Users. In addition, Blendedd may retain certain information in order to prevent identity theft and other illegal activities after an approved deletion. Removed information may remain in archives, but will not be available to other Users or third parties.</p>
				<br />
				<h3>How do we Protect User Information ?</h3>
				<br />
				<p><b>Information Security.</b> Blendedd will use a variety of security precautions to protect the security and integrity of all User information, in accordance with this Privacy Policy and all applicable laws. Each User's personal information is protected in several ways. Access by a User to his or her personal information is available through a password and unique customer ID selected by the User. This information is encrypted through the Website with Secure Socket Layer technology (SSL) and is also encrypted when it is stored by Blendedd to prevent unauthorized parties from viewing such information. Also, Blendedd performs regular malware scanning of the Blendedd website and all servers and computers used by Blendedd to support the Website. All Blendedd employees are required to adhere to Blendedd's security and confidentiality procedures and undergo training related to maintaining the security of User personal information.  </p>
				<p>In order to most efficiently serve our Users, credit card transactions are handled by established third-party banking and processing agents. They receive the information needed to verify and authorize your credit card or other payment information.</p>
				<p>However, as no storage or transmission is completely secure, we cannot guarantee that no breaches in security will be made. Without limitation of the foregoing, we cannot be responsible for the actions of unauthorized third parties that breach our security, and by using this Website you acknowledge that, while Blendedd will make every effort to protect Users' personal information, Blendedd is not liable if Users' personal information is viewed or tampered with by a third party. If Blendedd becomes aware of a data breach of the information stored on or for its Website, Blendedd will take reasonable efforts to notify Users of such a security breach within seven business days of becoming aware of the data breach. These efforts may include, but are not limited to, an email notification and/or an announcement on the Website.</p>
				<br />
				<h3>Other Information for Our Users</h3>
				<br />
				<p><b>Links.</b> The Website may contain links that lead to other websites, and Blendedd is not responsible for the privacy practices, content, and/or activities of these linked websites. Nonetheless, we seek to protect the integrity of our Website and welcome any feedback about these external websites. Users should keep this provision in mind whenever they follow a link to an external website and review the separate privacy policy terms of the external sites to which they are led. This Privacy Policy is applicable only to Blendedd and the information that we collect. </p>
				<p><b>Foreign Website Users.</b> Blendedd is a United States-situated company and is subject to the applicable state and federal laws of the United States. Users accessing the Website and its services must consent to the use and disclosure of information in accordance with this Privacy Policy and applicable governmental law.</p>
				<p><b>Eligibility.</b> All Users of the Website must be at least 18 years old. Blendedd does not knowingly collect, use, or disclose personal information from Users who are under the age of 18 or otherwise without the authority, right, or capacity to represent themselves. If a User matches any of the aforementioned criteria, he or she is prohibited from both the access and usage of the Website, unless a legally authorized representative is so using the Website on the User's behalf (i.e. a parent).</p>
				<p><b>Terms of Use.</b> This Privacy Policy forms part of, and is subject to, the provisions of Blendedd's Terms of Use.</p>
				<p><b>Effective Date and Changes to the Privacy Policy.</b> This Privacy Policy is effective as of March 1, 2015.We reserve the right to change this Privacy Policy at any time. Such changes, modifications, additions, or deletions shall be effective immediately upon notice thereof, which may be given by means including, but not limited to, issuing an email to the email addresses listed by registered Users and posting the revised Privacy Policy on this page. You acknowledge and agree that it is your responsibility to maintain a valid email address as a registered User, review this Website and this Privacy Policy periodically, and to be aware of any modifications. Your continued use of the Website after such modifications will constitute your: (a) acknowledgment of the modified Privacy Policy; and (b) agreement to abide and be bound by the modified Privacy Policy.</p>
				<br />
				<h3>If you have any questions regarding this Privacy Policy, please contact us at <a href="mailto:support@blendedd.com">support@blendedd.com</a></h3>
			</div>
		</div>
	</div>
</div>